# Generated by Django 2.2.6 on 2019-12-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crf_predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('game', models.CharField(max_length=100)),
            ],
        ),
    ]
